// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Tauri IPC command: Retrieves current minimize-to-tray preference. */
	getMinimizeToTray: () => __TAURI_INVOKE<boolean>("get_minimize_to_tray"),
	/**  Tauri IPC command: Updates current minimize-to-tray preference and persists to disk. */
	setMinimizeToTray: (enabled: boolean) => __TAURI_INVOKE<null>("set_minimize_to_tray", { enabled }),
	/**  Tauri IPC command: Retrieves the entire persisted `AppSettings` struct. */
	getAppSettings: () => __TAURI_INVOKE<AppSettings>("get_app_settings"),
	/**  Tauri IPC command: Atomically updates and persists the full `AppSettings` struct. */
	updateAppSettings: (settings: AppSettings) => __TAURI_INVOKE<null>("update_app_settings", { settings }),
	/**  Tauri IPC command: Restores `AppSettings` to factory defaults and persists to disk. */
	resetAppSettings: () => __TAURI_INVOKE<null>("reset_app_settings"),
	/**  Returns application and runtime system diagnostic information. */
	getAppInfo: () => __TAURI_INVOKE<AppInfo>("get_app_info"),
	/**  Tauri IPC command: Returns system and process telemetry stats. */
	getSystemStats: () => __TAURI_INVOKE<SystemStats>("get_system_stats"),
	/**  Tauri IPC command: Opens the OS-specific application data directory in the native file explorer. */
	openAppDataDir: () => __TAURI_INVOKE<null>("open_app_data_dir"),
	/**
	 *  Returns the last `max_lines` lines of the backend log file, newest last,
	 *  as a single newline-joined string. Mirrors the S2B2S `get_recent_logs`
	 *  command so the Dev Console can reconcile its live stream with disk.
	 */
	getRecentLogs: (maxLines: number) => __TAURI_INVOKE<string>("get_recent_logs", { maxLines }),
	/**  Truncates the backend log file so the Dev Console starts clean. */
	clearLogs: () => __TAURI_INVOKE<null>("clear_logs"),
};

/* Types */
/**  Runtime platform and version metadata returned to the frontend by `get_app_info`. */
export type AppInfo = {
	/**  Product name from `tauri.conf.json` (via `PackageInfo`), not the crate name. */
	name: string,
	/**  App version from `tauri.conf.json` (via `PackageInfo`), not the crate name. */
	version: string,
	/**  Tauri framework version this binary was compiled against. */
	tauri_version: string,
	/**  Target operating system, e.g. `windows`, `macos`, `linux`. */
	os: string,
	/**  Target CPU architecture, e.g. `x86_64`, `aarch64`. */
	arch: string,
};

/**  Persistent application preferences saved as JSON in the OS app configuration directory. */
export type AppSettings = {
	/**
	 *  Controls whether closing the main GUI window minimizes the app to the system tray
	 *  instead of terminating the application process. Default is false.
	 */
	minimize_to_tray: boolean,
	/**  Controls whether the application starts silently minimized to the system tray on launch. */
	start_minimized?: boolean,
	/**  Controls whether the application checks for updates on startup. */
	check_updates_on_launch?: boolean,
	/**  Selected theme accent color ID (e.g. "cyan", "emerald", "violet", "amber", "rose"). */
	theme_accent?: string,
	/**  Whether the main window restores its last size on startup. */
	remember_window_size?: boolean,
	/**  Whether the main window restores its last position on startup. */
	remember_window_position?: boolean,
	/**  Last persisted window width in physical pixels (0 = unset). */
	saved_window_width?: number,
	/**  Last persisted window height in physical pixels (0 = unset). */
	saved_window_height?: number,
	/**  Last persisted window X in physical pixels (`i32::MIN` = unset). */
	saved_window_x?: number,
	/**  Last persisted window Y in physical pixels (`i32::MIN` = unset). */
	saved_window_y?: number,
};

/**  System and process diagnostic telemetry returned by `get_system_stats`. */
export type SystemStats = {
	process_id: number,
	os: string,
	arch: string,
	tauri_version: string,
};

